# Generated by Django 4.2.5 on 2023-09-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_hire_date_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(choices=[('Backend Development', 'Backend Development'), ('Django Development', 'Django Development'), ('Python Development', 'Python Development'), ('Financet', 'Finance'), ('Food and Veberage (F&B)', 'Food and Veberage (F&B)'), ('Human Resource (HR)', 'Human Resource (HR)')], on_delete=django.db.models.deletion.CASCADE, to='emp_app.department'),
        ),
    ]
