# Generated by Django 4.2.5 on 2023-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('freelance', models.CharField(default='NOT', max_length=50, null=True)),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=14)),
                ('languages', models.CharField(default='Bangla, English', max_length=100)),
                ('skype', models.CharField(max_length=50, null=True)),
                ('instagrame', models.CharField(default='sagor_luc', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
