# Generated by Django 4.2.5 on 2023-09-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_myprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, null=True)),
                ('home_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_obj', to='profile_app.myprofile')),
            ],
        ),
    ]
