# Generated by Django 4.2.5 on 2023-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_homeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprofile',
            name='work_as',
            field=models.CharField(default='Software Engineer', max_length=100),
        ),
    ]
