# Generated by Django 4.2.5 on 2023-09-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_homeprofile_work_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50)),
                ('complate_project', models.CharField(max_length=50)),
                ('happy_customer', models.CharField(max_length=50)),
                ('award_won', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profile_app.myprofile')),
            ],
        ),
    ]
