# Generated by Django 4.2.5 on 2023-09-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_achivement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('project', models.CharField(max_length=100, null=True)),
                ('client', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('preview', models.URLField()),
                ('image1', models.ImageField(upload_to='photos/portfolio1')),
                ('image2', models.ImageField(upload_to='photos/portfolio2')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_portfolio', to='profile_app.myprofile')),
            ],
        ),
    ]
