# Generated by Django 4.2.5 on 2023-09-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0006_myportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('blog_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='photos/blog_image')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profile_app.myprofile')),
            ],
        ),
    ]
