# Generated by Django 4.2.5 on 2023-09-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0006_myportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='profile_app.myprofile')),
            ],
        ),
    ]
