# Generated by Django 4.2.5 on 2023-09-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_myportfolio'),
        ('contact_app', '0002_remove_contactinformation_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('x', models.URLField(blank=True)),
                ('instagrame', models.URLField(blank=True)),
                ('linkdin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='profile_app.myprofile')),
            ],
        ),
    ]
